# frozen_string_literal: true

source 'https://rubygems.org'

gem 'ffi', '~> 1.15', '>= 1.15.5' if Gem.win_platform? # Windows only
gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.35'
gem 'rubocop-rspec', '~> 2.12'
gem 'selenium-devtools', '= 0.125.0'
gem 'selenium-webdriver', '= 4.22.0'