# frozen_string_literal: true

source 'https://rubygems.org'
source "https://rubygems.pkg.github.com/seleniumhq" 
gem 'ffi', '~> 1.15', '>= 1.15.5' if Gem.win_platform? # Windows only
gem 'rake', '~> 13.0'
gem 'rspec', '~> 3.0'
gem 'rubocop', '~> 1.35'
gem 'rubocop-rspec', '~> 2.12'
gem "selenium-webdriver", "4.8.5.nightly.fix.pre.sm.pre.20230228"
gem 'webdrivers', '~> 5.1'
gem 'ffi', '~> 1.15', '>= 1.15.5'