# Tox (https://tox.wiki/) is a tool for running tests in multiple
# virtualenvs. This configuration file will run the test suite on all
# supported python versions. To use it, run "tox" from this directory.
#
# For a specific environment, run: "tox -e <env>" (i.e.: "tox -e py314")
#
# This tox configuration will skip any Python interpreters that can't be found.
# To manage multiple Python interpreters for covering all versions, you can use
# pyenv: https://github.com/pyenv/pyenv


[tox]
env_list =
    py310
    py311
    py312
    py313
    py314
skip_missing_interpreters = True

[testenv]
description = run tests
passenv = *
deps =
    -r requirements.txt
commands =
    # "-vv" means extra verbose
    pytest -vv -n auto {posargs:.}
